### ISSUE TITLE
Player can increasingly add upward velocity while paused and "slingshot" themselves

### ISSUE THREAD

**Issue by tanisd** [nbaines/2DPlatformerPrototype#2]
While the Pause menu is open, the Player can still press the Jump key to add to their upward velocity. Since the Player is still on the ground, each press of the Jump key will add together. When unpaused, this built-up velocity will launch/slingshot the player upward, up to a very large degree.

**Comment by nbaines** [comment]
Fixed this one & pushed a change for it, should work on all levels.
